{
	"user107": "Reminder",
	"manage277": "Personnel(s)",
	"manage88": "This is the default role of the company, which has partial function and data permissions and the role settings cannot be changed.",
	"manage54": "Add a New External Role",
	"manage96": "Check plants authorized to the member",
	"manage131": "External Role",
	"manage269": "\\\"External Role\\\" is used to separate external businesses or users from different functions.",
	"manage270": "Please enter external role name",
	"manage272": "Sure to terminate the relationship with these users? After that, the objects to which the business is associated with these users (such as plants, devices, etc,) will be deauthorized.",
	"manage273": "Sure to terminate the relationship with these businesses? After that, the objects to which the business is associated with other businesses (such as plants, devices, etc,) will be deauthorized.",
	"manage302": "Founder Info",
	"user52": "Business name already existed",
	"device37": "Username already existed",
	"manage276": "Please enter phone number or E-mail",
	"user144": "Phone number already existed",
	"user145": "E-mail already existed",
	"device_management40": "Check plants authorized to the business",
	"manage125": "Sure to terminate the relationship with current business? After that, the objects to which the business authorized to current business (such as plants, devices, etc,) will be deauthorized.",
	"manage129": "Sure to terminate the relationship with the user? After that, the objects to which the business authorized to the user (such as plants, devices, etc,) will be deauthorized.",
	"manage271": "Check plants authorized to the user",
	"manage274": "Timestamp",
	"manage275": "Add a New Business",
	"device210": "Level 5 region",
	"device212": "Level 1 region",
	"device213": "Level 3 region",
	"device214": "Level 4 region",
	"device217": "Level 2 region",
	"plant200": "Region",
	"device_management6": "Read&Write/Upgrade Records",
	"device_management7": "Read&Write/Upgrade Records",
	"device_management9": "Upload/Edit Firmware Info",
	"device_management21": "Read&Write/Upgrade Records",
	"user10": "Reset",
	"user12": "Deauthorize",
	"device220": "I Got it.",
	"manage5": "Add a New Member",
	"manage10": "Clone",
	"manage11": "Clone Role",
	"manage12": "Set up Plant",
	"plant10": "Check Plant List",
	"manage16": "Check Plant Details",
	"plant_detail42": "Check Sub-system/Device",
	"manage19": "Add a New Sub-system/Device",
	"manage20": "Edit Sub-system/Device",
	"plant_detail43": "Delete Sub-system/Device",
	"plant_alert23": "Check Plant Alerts",
	"manage22": "About Plant",
	"manage25": "Delete Member",
	"plant_detail44": "Correlated Tag",
	"plant_detail45": "Delete Tag",
	"manage27": "Check Device Details",
	"manage28": "Check Alert Info",
	"manage29": "Check Linkage Info",
	"plant_detail48": "Check Read&Write Records",
	"plant_detail49": "Check Upgrade Records",
	"plant_alert25": "Check Alert List",
	"manage30": "Check Alert Details",
	"manage31": "Check Device List",
	"manage33": "Check Firmware List",
	"manage35": "Check Firmware Details",
	"manage36": "Delete Firmware",
	"manage42": "Check Role List",
	"manage44": "Edit Role",
	"manage45": "Delete Role",
	"manage47": "Check Tag List",
	"manage49": "Add a New Tag",
	"manage50": "Edit Tag",
	"manage52": "Delete Tag",
	"user16": "Click to select the object",
	"plant255": "Select Month",
	"plant12": "Status",
	"plant13": "Done",
	"plant24": "Importance",
	"plant_detail78": "No repetition",
	"device211": "Satellite",
	"plant_detail87": "Distribution",
	"plant_detail95": "This Month",
	"manage62": "E-mail",
	"plant_detail99": "Mandatory",
	"plant26": "Please enter plant address",
	"manage67": "Role field cannot be blank. If there is no role option, please contact admin for permission.",
	"manage68": "Department name/Organization name",
	"plant_delete2": "Sure to delete the device?",
	"plant_detail101": "Please configure the properties of meter transformer according to the installation of meter.",
	"device30": "Please Notice",
	"user35": "How to obtain?",
	"plant_delete4": "Sure to delete sub-system? After that, it may cause the loss of all history data, please be cautious.",
	"plant_detail102": "Make sure that sub-devices (such as inverters, meters, modules, and etc.) are powered on and communicate with gateway devices (such as loggers) properly. If you can not find target gateway device, please refresh the list.",
	"manage73": "Common User (Default)",
	"manage75": "Sure to delete this member？",
	"manage77": "After resetting the password, system will not send SMS or E-mail to notify members. Please inform the members of the new password to ensure the normal use.",
	"manage79": "Please enter role name",
	"manage80": "Sure to delete the role?",
	"manage81": "Role name is not allowed to be the same under the same business.",
	"manage82": "Enter role description",
	"manage84": "Add a New Role",
	"manage85": "Phone Number",
	"manage86": "Function Permission",
	"plant_detail111": "Device has been added to other plant. Unable to add again.",
	"manage89": "Sure to delete the tag?",
	"plant_list16": "Top 10",
	"plant_list17": "Daily Self-used Consumption",
	"plant_list18": "Monthly Self-used Consumption",
	"manage90": "Please enter tag describtion",
	"plant_detail112": "Not Configured",
	"plant_detail114": "Add a Sub-system",
	"plant30": "Today",
	"plant_detail119": "Configuration Status",
	"plant_detail121": "Apply to",
	"plant_detail122": "Configured",
	"plant31": "CT",
	"plant_detail126": "Current Ratio",
	"plant_detail130": "Grid（Grid Power/Grid Status/Grid Feed-in/Energy Purchased）",
	"manage94": "Management",
	"manage98": "Tag",
	"manage99": "Influence",
	"plant_alert29": "Last Trigger Time",
	"plant_alert30": "Problem Description",
	"plant_alert31": "Trigger Condition",
	"plant_alert36": "Customized Alert",
	"plant_alert38": "Influence Production",
	"plant_alert39": "Influence Safety",
	"plant_alert40": "Influence Production&Safety",
	"device36": "Extended Services",
	"plant_detail142": "Parent Device",
	"plant_detail143": "Parent Device Communication Status",
	"plant_detail145": "Sub-system/Device",
	"plant_detail146": "Offline Devices",
	"plant_alert42": "Alerting Devices",
	"plant_alert43": "Normal Devices",
	"device42": "Please enter system name",
	"manage102": "Applicable Object",
	"plant_detail150": "Single-phase System",
	"plant_detail153": "Installation Site",
	"plant_detail155": "Production Overview",
	"plant_detail158": "In 10 mins",
	"plant65": "In 3 Days",
	"plant66": "Last 7 Days",
	"manage103": "Visible View",
	"manage104": "Device Alert",
	"device_management45": "Alert Line",
	"manage114": "Phone number",
	"plant69": "Reason 1",
	"plant70": "Solution 1",
	"manage115": "E-mail",
	"plant72": "About",
	"plant73": "Edit Plant Info",
	"plant_alert44": "Alerts",
	"plant_detail164": "Three-phase System",
	"plant83": "Contact Number",
	"manage118": "Describtion",
	"device62": "Devices",
	"plant110": "Basic Info",
	"manage134": "Reset Password",
	"device80": "Enter device name/SN",
	"plant_detail187": "CT installation direction (Click Arrow to Switch)",
	"manage148": "Edit member",
	"manage149": "Describtion",
	"manage157": "Portlet",
	"manage159": "Data Permission",
	"manage170": "Name",
	"manage173": "Member/Role",
	"manage175": "Please enter tag name",
	"plant_detail203": "Apply to",
	"manage179": "Member Name",
	"manage180": "Alert Name",
	"plant147": "Add a New Sub-device",
	"plant152": "Reasons&Solutions",
	"plant155": "Name/SN",
	"plant156": "System",
	"manage181": "Name",
	"plant171": "Device Name",
	"plant_alert59": "Alerts",
	"plant_detail254": "Select Parameters",
	"plant_detail258": "Offline",
	"user83": "Name",
	"manage219": "Original Password",
	"creat_plant9": "Plant Info",
	"manage224": "Type",
	"manage225": "Super admin",
	"plant_detail262": "Founder",
	"plant_detail264": "Plant ID",
	"manage226": "Last Login",
	"manage237": "Role",
	"manage238": "Activated",
	"plant179": "Unactivated",
	"plant_alert64": "Alert Details",
	"manage239": "Tag Management",
	"device134": "Member name field cannot be blank",
	"device137": "Address field cannot be blank",
	"plant_alert74": "Plant Associated Alerts",
	"plant181": "Plant Associated Devices",
	"plant182": "Plant name field cannot be blank",
	"plant183": "Details",
	"plant184": "Loc",
	"plant_detail276": "Authorize to a New Member",
	"plant_detail277": "Administrative Area",
	"plant_detail278": "Administrative area field cannot be blank",
	"manage240": "Your account has been removed. Contact super admin for more details.",
	"plant191": "Select Systems in Batch",
	"manage241": "Please enter new password",
	"plant_detail280": "How to obtain sub-device ?",
	"plant_alert75": "Device Associated Alerts",
	"plant193": "Device Associated Plants",
	"plant_detail281": "Normal Communication",
	"plant_detail282": "Location field cannot be blank",
	"device_management95": "Installed capacity field cannot be blank",
	"plant90": "My Watchlist",
	"manage151": "Copy permission of【XX】 and create a new role",
	"plant197": "Up to 10",
	"plant17": "Cloudy",
	"plant18": "Sunny",
	"plant19": "Foggy",
	"plant20": "Snowy",
	"plant21": "Drizzling",
	"plant22": "Heavy rain",
	"device_management66": "Thunder",
	"plant_detail104": "No Communication Status",
	"plant_alert26": "No Alert Status",
	"plant_detail105": "Data Privileges are Determined by the Plant",
	"manage106": "My Plant",
	"manage109": "All Plants",
	"manage110": "Company-wide Visibility",
	"manage83": "Please enter role name",
	"app13": "Peak Hour Ranking",
	"plant_list22": "PR Ranking",
	"device_management63": "Trees",
	"all7": "Dashboard",
	"manage65": "PR",
	"plant_detail107": "Peak Hours",
	"manage305": "The number of tags has exceeded the upper limit of 50.",
	"device31": "Data Privileges are Determined by the Device",
	"plant9": "Auto-adding",
	"plant_alert47": "No Influence",
	"plant_detail253": "Temp",
	"manage87": "This is the default role of the company, which has full function and data permissions and the role settings cannot be changed.",
	"plant_alert50": "Alert Object",
	"user15": "Click to Switch",
	"plant_detail117": "The following is",
	"plant_detail118": "Here is current flow simulation diagram of plant system. Please set data source.",
	"all9": "O&M",
	"manage105": "O&M",
	"user8": "Next",
	"user11": "Register",
	"user17": "Phone",
	"user18": "E-mail",
	"user19": "Username",
	"user20": "Switch to phone registration",
	"user21": "Switch to E-mail registration",
	"user22": "Your account already registered in XX business account. You can [Click here] login directly or create a new business account. Please make sure the new business account and password are in consistent with your current account.",
	"user23": "Enterprise",
	"user24": "At least 6 characters",
	"user30": "I have read and agreed",
	"manage69": "No repetition",
	"user36": "Log In",
	"user37": "Please select the business",
	"user38": "Account does not belong to any businesses yet. Please register a business account.",
	"user43": "Enter Account Info",
	"user44": "Enter Business Info",
	"user46": "Created!",
	"user47": "Your account already existed. It is required to create a new business account for Pro Version. Please make sure the new business account and password are in consistent with your current account.",
	"manage92": "How to select business sector?",
	"manage95": "Different sectors are designed for different businesses with different requirements. Each sector has its unique capabilities. Please select the appropriate business sector according to your own positioning and requirements.",
	"manage97": "Apply to installers, O&M operators",
	"plant46": "Select Business Sector",
	"user53": "Finished and Log In",
	"login7": "Username",
	"user56": "Invalid verification code",
	"user57": "Please log in with new password",
	"plant78": "Weather data acquisition failed, please click \\\"Retry\\\" to retrieve again.",
	"user59": "Name",
	"user60": "Password",
	"user62": "Please confirm",
	"user66": "Inconsistent password",
	"user67": "Send",
	"manage121": "Business Type",
	"manage124": "Businesses",
	"manage127": "About",
	"manage128": "Business Area",
	"user74": "New Password",
	"device_management64": "Retry",
	"user77": "Registration Info",
	"manage172": "Contact Info",
	"manage174": "Enterprise",
	"manage176": "Individual",
	"manage182": "O&M Sector",
	"manage183": "Device Sector",
	"plant170": "Business Name",
	"plant173": "Basic Info",
	"user82": "Verification Code",
	"plant_detail259": "Phone Number",
	"plant_detail260": "E-mail",
	"manage314": "Undo",
	"manage315": "Exceed the upper limit",
	"manage316": "Enter business name",
	"manage317": "Enter name/phone number/E-mail",
	"manage318": "Select Businesses",
	"manage319": "Select Users",
	"manage320": "User",
	"user136": "Completed",
	"user137": "Confirm Account",
	"user139": "Business sector field cannot be blank",
	"user140": "At least 6 Characters",
	"user141": "Name field cannot be blank",
	"user142": "Verification code field cannot be blank",
	"user143": "Individual",
	"manage323": "Username",
	"user146": "Please tick to continue",
	"user147": "Already have a business account? Log In.",
	"user148": "Username field cannot be blank",
	"user63": "T&Cs",
	"user39": "Enter E-mail or Phone Number",
	"manage116": "Apply to manufacturers, distributors",
	"user134": "The browser you are using is not supported for now or the version is too old. For better experience, it is recommended to use latest version of Chrome, Firefox, Safari browser.",
	"plant_detail355": "Experience with current browser",
	"plant_detail356": "Download Firefox",
	"manage325": "Download Chrome",
	"creat_plant1": "If your gateway device is used only for one plant, auto-adding is recommended. System will automatically add sub-devices to the plant based on the connection between the gateway device and the sub-device.\nIf your gateway device is used for multiple plants, manual-adding is recommended. You can select the suitable sub-devices based on the actual usage of sub-device.\n\nNotice: Make sure that sub-devices (such as inverters, meters, modules, and etc.) are powered on and communicate with the gateway device (such as loggers) properly. If you have not found the target sub-device, please refresh the list of sub-devices.",
	"plant5": "Create a New User",
	"user7": "Create a New User",
	"plant8": "Add a new device directly",
	"user48": "Account or password error",
	"user51": "Me",
	"plant60": "Select Substitution Objects",
	"plant_detail154": "Only sub-device is added via manual-adding can be added again.",
	"device_management41": "Current plant is not from inside, click to view permissions to current plant",
	"device_management43": "List of Function Permissions",
	"manage112": "Here are function permissions to the current plant. Function permissions for each member are determined by his role.",
	"plant80": "No result found, create an account for him?",
	"plant81": "Select at least one applicable subject",
	"plant_alert49": "Access",
	"plant_delete9": "Sure to delete external role",
	"manage119": "Select function permissions of the external role for our plants",
	"user68": "Enter username",
	"plant_detail171": "Device has been added to other plant. Unable to add again.",
	"manage122": "Name",
	"manage123": "Describtion",
	"manage126": "Edit External Role",
	"plant_detail173": "Sub-device is the device connected to gateway device. (e.g. Logger is a gateway device, then inverter is a sub-device.)",
	"plant_detail174": "Under what circumstances to use Auto-adding or Manual-adding?",
	"plant_detail175": "Why is only manual-adding available?",
	"plant_detail176": "If the gateway device is added to the plant via auto-adding, system will not support adding the gateway device to another plant, so only the gateway device which is added via manual-adding can be added to other plants again.Therefore, if you could only add your sub-device via manual-adding, which means the gateway device is initially added to the plant via manual-adding.",
	"plant_detail178": "What is sub-device?",
	"manage130": "External Relation",
	"plant_detail180": "Name",
	"manage132": "Authorized External Role",
	"user73": "Old Password",
	"user78": "Modified By",
	"plant160": "Create a  New Business",
	"plant164": "Create Now",
	"plant_detail239": "Search Results",
	"user124": "Old password incorrent",
	"user125": "Confirm new password",
	"user126": "Enter new password",
	"user127": "Enter old password",
	"user128": "Modify Phone Number",
	"user129": "Modify E-mail Address",
	"user131": "Modify Your Name",
	"manage266": "External role name field cannot be blank",
	"manage267": "Select function permissions of the external role for our devices",
	"manage268": "Copy permissions of【XX】and create a new external role",
	"manage308": "Add User Relationship",
	"manage309": "Add Business Relationship",
	"plant_detail74": "Uploading: X1X data. Succeed: X2X data. Fail: X3X data.",
	"device_management28": "Device control function is not available",
	"device_management29": "Device upgrade function is not available",
	"device_management30": "Batch Import",
	"plant_detail141": "Inputs",
	"device_management48": "Please Enter SN. (SNs are separated by commas.)",
	"device_management51": "Upload",
	"user64": "Verification code has expired. Please try again.",
	"device78": "Device Log",
	"plant_detail184": "Operation Log",
	"plant_detail185": "Control Log",
	"plant_detail186": "Upgrade Log",
	"device84": "Sure to delete the device?",
	"device_management55": "Device has not been activated yet, unable to upgrade firmware",
	"device_management56": "Device has not been activated yet, unable to control device",
	"manage169": "Download failure list",
	"plant162": "Activation Status",
	"manage220": "Device List",
	"manage278": "Please Select Command",
	"manage282": "Please Enter a Positive Integer Greater Than 1 and Less Than 10",
	"manage283": "Remote Command",
	"manage286": "SN Already Existed",
	"manage287": "Done",
	"manage300": "Processing",
	"manage301": "Enter SN to Import",
	"manage4": "Search for System-wide Businesses",
	"manage23": "Check Authorization",
	"plant_detail69": "You can do the following operations to the gateway/logger XX",
	"user34": "Your account has been changed. Please log in again. You can contact super admin for details.",
	"plant29": "Please enter a gateway/logger SN which belongs to the plant, system will get data from the gateway/logger and its sub-system. You can skip it now and do it later in Plant Details.",
	"member4": "You are going to authorize plants to internal members in batch, which means your colleagues can see these plants as well.",
	"plant50": "Commissioning Date",
	"plant_alert34": "In Operation",
	"plant_alert35": "Not in Operation",
	"plant_delete7": "Sure to remove the plant? After that, all members under the business will not be able to check the plant.",
	"plant57": "Other internal members are eligible to check the plant after your authorization. You can skip it now and do it later in Plant Details.",
	"plant_detail151": "Manual-adding",
	"plant67": "Authorization",
	"device_record13": "If you are the founder of part of selected plants, please be noted that authorizing businesses in batch only applys to plants created by yourself.",
	"plant74": "You are going to authorize plants to other businesses in batch, which means other businesses can see these plants as well.",
	"plant75": "You are not the plant founder, which can only authorize the plant to internal members of the company",
	"plant76": "Other users are eligible to check the plant after your authorization. You can skip it now and do it later in Plant Details.",
	"plant77": "Other business units are eligible to check the plant after your authorization. You can skip it now and do it later in Plant Details.",
	"plant79": "If you are not the founder of all selected plants, then only authorizing internal members in batch is allowed.",
	"plant_detail167": "Sub-device Adding",
	"plant89": "Authorize to Businesses in Batch",
	"plant_detail172": "Here is a gateway/logger list which sub-devices are added via manual-adding. Please click gateway/logger to select sub-devices again.",
	"plant115": "Select Businesses who have Built Relationships",
	"plant121": "Authorize",
	"manage162": "Check Tag Belonged to",
	"plant127": "Search for System-wide Users",
	"plant128": "Coordinate",
	"plant_detail200": "Operation Status",
	"plant_detail202": "Authorize Users",
	"plant_detail229": "Add a New Gateway/Logger",
	"plant_detail238": "Authorize Internal Members",
	"manage218": "Authorize Business Units",
	"plant178": "Gateway/Logger",
	"device135": "Alert",
	"plant_delete13": "Sure to terminate the relationship between the user and the plant? After that, the user will not be able to check the plant.",
	"plant_delete14": "Sure to terminate the relationship between the business and the plant? After that, all members under the business will not be able to check the plant.",
	"manage310": "Select Users who have Built Relationships",
	"manage313": "Authorize to Internal Members in Batch",
	"plant138": "Country",
	"plant_detail82": "Environmental & Economic Benefits",
	"plant7": "Replace existing gateway/logger",
	"plant_detail68": "XX Sector",
	"device82": "Click here to download",
	"manage186": "User Manual",
	"user79": "Simple Version",
	"user80": "Full Version",
	"plant165": "Battery",
	"plant_detail194": "The progression rules of logger firmware version have not been recorded or have been duplicated.\n",
	"manage249": "Please Select XX",
	"manage311": "Hybrid Power Cabinet",
	"plant239": "Water pump",
	"plant240": "Fan",
	"plant241": "Solar Radiation Spectrometer",
	"plant242": "Solar Tracker Controller",
	"user113": "About Bliq",
	"plant117": "Exit",
	"plant145": "Permission has not been granted. Please contact Super Admin.",
	"plant_detail323": "If the gateway/logger is used for microinverter and the gateway/logger is used for multiple plants, please select Manual-adding here.",
	"manage6": "Add a Subordinate Dep.",
	"manage7": "Add a Parallel Dep.",
	"manage8": "Edit Dep.",
	"manage9": "Delete Dep.",
	"manage37": "Check Company Structure",
	"manage38": "Check Dep./Member List",
	"manage39": "Add a New Dep./Member",
	"manage40": "Edit Dep./Member",
	"manage41": "Delete Dep./Member",
	"manage64": "You have moved the user to other department. Please select the objects to terminate the relationship. (If not, the relationship will be reserved. ) ",
	"manage66": "Department",
	"manage70": "Department Belonged to",
	"manage71": "Superior Department Belonged to",
	"manage72": "Department Name",
	"manage74": "Sure to delete the department?",
	"manage78": "Role is used to control the viewing scope of objects (e.g. plant) and the functions they can use. When setup is done, members can assign role in [Add a New Number-Dep./Member].",
	"manage107": "Plants of My Dep.",
	"manage108": "Plants of My Dep.&Downstream Dep.",
	"manage111": "My Dep./Me",
	"device_management42": "My Dep./Members of My Dep.",
	"device_management44": "My Dep.&Downstream Dep./Members of My Dep.&Downstream Dep.",
	"manage113": "All Dep./Members",
	"manage117": "Company Structure",
	"manage135": "Department name field cannot be blank",
	"manage139": "Add a New Department",
	"manage158": "Modify the deparment level of receiver",
	"manage160": "Remove receiver from business unit",
	"manage161": "Modify the department of receiver",
	"manage178": "Dep./Member",
	"manage185": "Edit Department",
	"manage187": "External Management",
	"manage256": "Check External Management",
	"plant_detail374": "Details",
	"plant_detail377": "Total Consumption",
	"device_management98": "There are unconfigured meters in your plant. Please click the unconfigured meter to complete the configuration. Otherwise, the meter data will not be shown in the plant.",
	"device_management99": "No longer appear",
	"device_management100": "Configuration reminder for meter",
	"plant258": "No data",
	"login1": "Installer",
	"login2": "O&M Provider",
	"login3": "Distributor",
	"login4": "Manufacturer",
	"meter_configure1": "System has found unconfigured meters in the plant. Please click \\\"Go to configure\\\" to configure. Otherwise the meter data will not be displayed in the plant.",
	"meter_configure2": "Go to configure",
	"meter_configure3": "Next time",
	"plant_list1": "Normal Mode",
	"plant_list5": "Following parameters will be sorted automatically",
	"plant_list6": "Peak Hours Today =  Daily Production / Installed Capacity",
	"plant_list9": "Ascending order according to peak hours today",
	"plant_list10": "Descending order according to peak hours today",
	"plant_alert1": "Alerts in Plant",
	"plant_device1": "Devices in Plant",
	"plant_device2": "System",
	"me3": "Avatar",
	"me4": "Choose from Album",
	"me5": "Take Photo",
	"depot1": "Device Library",
	"depot2": "Device Library",
	"product1": "Product list",
	"product2": "Product Management",
	"product3": "Edit Product",
	"product4": "Transfer Product",
	"device_file1": "Device File",
	"message2": "It refers to the system will monitor the number of consecutive triggers of different alarms of each device under the power station, and send an alarm message when the set number of times is reached. To avoid the situation of sending alarm messages continuously.",
	"message3": "Push Limit",
	"message4": "System will restrict the upper limit of daily alert messages of each device to avoid excessive information.",
	"message5": "Positive Integer (1-50)",
	"me6": "Change Avatar",
	"me7": "Upload Again",
	"meter_configure4": "Current ratio must be greater than 0",
	"meter_configure5": "Duplicate locations cannot be selected",
	"meter_configure6": "Meter does not support this configuration",
	"manage336": "Do you want to delete this department?",
	"command1": "Read Power Control Timeout",
	"command2": "Set Power Control Timeout",
	"command3": "Power Control",
	"command4": "Read Power Control",
	"command5": "Set Power Control",
	"command6": "Read Active Power",
	"command7": "Set Active Power",
	"command8": "Read Reactive Power",
	"command9": "Set Reactive Power",
	"oem1": "Phase",
	"device5": "Device Library",
	"device6": "Device Status Overview",
	"device7": "Device Activity Overview",
	"device8": "Daily Activity",
	"device9": "Monthly Activity",
	"device10": "Yearly Activity",
	"device11": "Statistics Default: Business Time Zone",
	"device12": "Daily Upload Record",
	"device13": "Monthly Upload Record",
	"device14": "Yearly Upload Record",
	"device15": "Device Correlation",
	"device16": "Uncorrelated System",
	"device17": "Correlated System",
	"device18": "Added Device",
	"device19": "Devices Not Added",
	"device20": "Correlated System Status",
	"device21": "Correlated",
	"device22": "Uncorrelated",
	"device23": "Starting Time",
	"device24": "Ending Time",
	"product5": "Product Set: A set of products with same protocol, same data and same function.",
	"product6": "Product Name",
	"product7": "sensor",
	"product8": "Protocol Code",
	"product9": "Transfer",
	"product10": "Notice: After the transfer, you and your colleagues will lose the right to upload firmware and create batch tasks, which will be transferred to the new company.",
	"device28": "The following files did not find a matching collector, a total of 2",
	"device26": "Please Enter Firmware Version",
	"device27": "XX selected, API Importing, Unable to Delete",
	"plant_list2": "Analysis Mode",
	"plant_list3": "About Analysis Mode",
	"plant_list4": "Analysis Mode is suitable for plants in the same area, which can operate normalized parameter comparison to identify plants with problems.",
	"plant_list7": "Power Normalized = Production Power / Installed Capacity",
	"plant_list8": "Power Normalized",
	"plant_list11": "Ascending order according to power normalized",
	"plant_list12": "Descending order according to power normalized",
	"plant_detail40": "System On/Off",
	"device_management1": "Single Import",
	"device_management2": "Please Upload EXCELE File",
	"device_management3": "Please Upload XX File",
	"device_management4": "Special Processing",
	"device_management5": "Add 20 Bytes",
	"device_management8": "Historical Data",
	"device_management10": "Device Management",
	"manage1": "Default External Role",
	"plant_detail34": "Total Yields",
	"plant_detail35": "Add Transformation Logic",
	"device_management11": "Logger Communication Mode",
	"device_management12": "PF Curve Enabled",
	"device_management13": "Voltage",
	"user1": "Registered",
	"plant_detail36": "Non-auto Shutdown",
	"device_management14": "Batch Deletion",
	"plant_detail37": "Non-auto Startup",
	"user2": "Please enter E-mail ",
	"device_record1": "Grid Level 1 Underfrequency Value",
	"device_record2": "Grid Level 2 Overfrequency Value",
	"device_management15": "Auto Shutdown",
	"device_management16": "Device Upgrade Mode",
	"device_management17": "Auto Startup",
	"device_record3": "Grid Level 1 Overfrequency Value",
	"device_record4": "Power Factor Set Value",
	"device_record5": "Grid Level 2 Undervoltage Value",
	"device_record6": "Grid Level 1 Undervoltage Value",
	"device_record7": "Clear Total Production",
	"device_record8": "Grid Level 2 Overvoltage Value ",
	"device_record9": "Clear Total Production Time",
	"device_record10": "Grid Level 1 Overvoltage Value ",
	"device_record11": "Clear Daily Production",
	"plant_detail38": "Off",
	"plant_detail39": "On",
	"device_management18": "Path",
	"device_management19": "Notice: If the gateway/logger you selected has sub-devices, these sub-devices will be imported synchronously.",
	"user3": "Please enter phone number",
	"plant_delete1": "Sure to terminate the relationship between the member and the plant? ",
	"device_management20": "Notice: If the gateway/logger you selected has sub-devices, these sub-devices will be deleted synchronously. Sure to delete the gateway/logger?",
	"device218": "Firmware List",
	"user4": "Personal Settings",
	"device219": "Remote Control",
	"plant2": "Label Processing",
	"user5": "Enter Country/Code",
	"manage2": "“XX\" wants to access your album",
	"all6": "Add Tags in Batch",
	"user6": "Select Business Type",
	"plant3": "Gateway/Logger List",
	"plant_detail41": "The following list is gateways/loggers which the sub-devices are added via manual-adding.",
	"manage3": "Sure to delete the business name?",
	"plant4": "Add",
	"user9": "Confirm",
	"app7": "Collapse",
	"app8": "Advanced Filter",
	"user13": "Settings",
	"plant6": "Follow",
	"device221": "Resend",
	"user14": "Log Out",
	"device223": "Related Version",
	"creat_plant2": "Creat a Plant",
	"creat_plant3": "Edit Plant",
	"manage13": "Set Plant",
	"manage14": "Delete Plant",
	"manage15": "Check Plant List",
	"manage17": "Check Plant Details",
	"manage18": "Check Sub-system/Device",
	"all8": "All",
	"manage21": "Delete Sub-system/Device",
	"manage24": "Authorized Members",
	"member2": "Delete Member",
	"app9": "Unfold",
	"manage26": "Check System",
	"plant_detail46": "Check Device Details",
	"plant_alert24": "Check Alert Info",
	"plant_detail47": "Check Linkage Info",
	"manage32": "Check Device Details",
	"manage34": "Check Firmware List",
	"device224": "Delete Firmware",
	"manage43": "Edit Role",
	"manage46": "Delete Role",
	"manage48": "Check Tag List",
	"manage51": "Delete Tag",
	"manage53": "Select Tags",
	"manage55": "Clone External Role",
	"plant11": "Authorize to a New User",
	"plant_detail51": "All Devices Offline",
	"plant_detail52": "Partial Devices Offline",
	"plant_detail53": "On",
	"plant_detail54": "String",
	"plant_detail55": "No.",
	"manage56": "Delete User",
	"login5": "Authorize to a New Business",
	"plant14": "Normal",
	"plant15": "PR Yesterday",
	"device_management22": "Brand",
	"manage57": "Delete Business",
	"device225": "Upload Firmware Info",
	"manage58": "XX tags",
	"command14": "Output Power Derating Factor",
	"plant_list14": "Top 10",
	"plant_list15": "Last 10",
	"plant_detail56": "Today XX",
	"plant_detail57": "This Year XX",
	"plant_detail58": "This Month XX",
	"plant_detail59": "Please enter XX",
	"plant_detail60": "Sure to delete XX?",
	"plant_detail61": "Top XX",
	"plant_detail62": "Last 10",
	"plant_detail63": "Last XX",
	"plant_detail64": "X1X has exceeded the upper limit. Upper Limit is X2X",
	"plant_detail65": "Here is current flow simulation diagram for XX plant. Please set data source.",
	"plant_detail66": "Yesterday XX",
	"plant_detail67": "Apply to XX",
	"device_management23": "A total of 20 devices were selected, including 8 gateways/loggers, sure to delete these 8 devices?",
	"device202": "Read XX",
	"device203": "Set XX",
	"device204": "Add XX",
	"device205": "Delete XX",
	"device206": "Edit XX",
	"plant_detail70": "XX field cannot be blank",
	"plant_detail71": "Authorize to XX",
	"plant_detail72": "XX does not exist",
	"plant23": "Total XX Plant(s)",
	"plant_detail73": "XX already existed",
	"member3": "Select Members",
	"plant_detail75": "XX cannot be repeated",
	"plant_detail76": "Check XX",
	"plant_detail77": "Please confirm",
	"plant_detail79": "Terminate User Relationship",
	"device207": "None",
	"device208": "XX Operation Log",
	"device209": "Obtaining",
	"device215": "DC",
	"device216": "AC",
	"app10": "Yuan ",
	"plant_detail80": "Select sub-device of XX",
	"device_management24": "X1X selected. X2XAPI imported, unable to delete. X3X imported manually, able to delete. Sure to delete X4X device(s)?",
	"plant_detail81": "Irradiance",
	"plant25": "Note",
	"plant_detail83": "Operating (Grid-connected/Production) ",
	"plant_detail84": "Definition",
	"plant_detail85": "Definition of commissioning date",
	"plant_detail86": "It is recommended that you choose grid-connected date for on-grid plants and production date for off-grid plants. \n",
	"plant_detail88": "No Devices",
	"plant_detail89": "Sure to delete XX device(s)?",
	"user25": "At least 6 characters",
	"plant_detail90": "and XX plants",
	"manage59": "Check Operation Log",
	"device29": "Check Device Library",
	"plant_detail91": "Plant XX System Layout",
	"user26": "XX E-mails at max.",
	"plant_detail92": "Peak Hours-Yesterday",
	"user27": "XX Phone Voices at max. Limit to Chinese Phone Number",
	"plant_detail93": "XX members",
	"manage60": "Please enter member name",
	"plant_detail96": "Total Cost",
	"manage61": "Limit to XX members",
	"plant_detail97": "There is X2X alert in X1X plant",
	"plant_detail98": "Results",
	"manage63": "Invalid E-mail format",
	"user28": "Invalid phone number format",
	"device_management25": "Failure",
	"user29": "Please enter",
	"creat_plant64": "Multiple results available. Choose one as your plant location.",
	"creat_plant4": "No results available. Choose your plant location manually.",
	"creat_plant5": "Created! Please do the following operations.",
	"plant_detail100": "Replace existing loggers",
	"device_management26": "Upgrade Successfully",
	"record9": "Enter device SN",
	"login6": "Terminate Business Relationship",
	"plant_delete3": "Sure to delete the device?",
	"creat_plant6": "Created!",
	"plant27": "Min.capacity (If you skip, there is no lower limit.)",
	"plant28": "Max.capacity (If you skip, there is no upper limit.)",
	"user31": "Send successfully",
	"user32": "System will automatically consider it as a failure if no command feedback is received after timeout. Please try again.",
	"user33": "If correlated version info remains the same when it exceeds timeout period, system will automatically consider the upgrade as a failure, please try again.",
	"device_management27": "Type/SN",
	"manage76": "Members",
	"plant_detail103": "Data is available till the previous day.",
	"record10": "Avg weather station data",
	"plant_detail106": "Enter sub-system name",
	"plant_detail108": "More",
	"plant_detail109": "You can tag the plant, which is convenient for you to spot it. You can skip it now and do it later in Plant Details.",
	"plant_detail110": "You can create a sub-system of the plant by adding devices into the sub-system, and get a seperate view on it. You can skip it now and do it later in Plant Details.",
	"plant_delete5": "Confirm Deletion",
	"device_management31": "Please enter firmware name",
	"plant_list19": "Yearly Self-used Consumption",
	"plant_detail113": "Confirm",
	"plant_delete6": "Delete Sub-system",
	"user40": "Close",
	"user41": "Why to add device",
	"user42": "Sorry, why to add device",
	"app11": "Click to Choose Devices",
	"plant_detail115": "Intelligence Selection",
	"plant_detail116": "Data Source",
	"user45": "Switch to E-mail",
	"plant_detail120": "Revise manually",
	"plant_detail123": "Intelligence selection will be reflected in 5-10mins. Please be patient.",
	"plant_detail124": "Set as Intelligence Selection",
	"plant_detail125": "Here is current flow simulation diagram for self-consumption plant. Please set data source.",
	"plant32": "Monday",
	"plant_detail127": "Production (Production Power/Capacity)",
	"plant_detail128": "Inverter data summation",
	"plant_detail129": "Meter data summation",
	"plant33": "Tuesday",
	"manage91": "Exceed upper limit of language selection",
	"plant34": "Wednesday",
	"plant_detail131": "Current Setting Method",
	"plant35": "Thursday",
	"plant36": "Friday",
	"plant37": "Saturday",
	"user49": "Error",
	"plant39": "Sunday",
	"user50": "Switch to Phone Number",
	"plant_detail132": "Click here",
	"plant_detail133": "COM Status",
	"plant_detail134": "Normal Communication",
	"plant40": "All Devices Offline",
	"plant41": "Partial Devices Offline",
	"plant_detail135": "Repeated selection is not allowed",
	"plant_alert27": "Alerting",
	"plant_alert28": "No Alerts",
	"plant_detail136": "Followed",
	"plant_detail137": "Unfollowed",
	"plant42": "Yesterday",
	"plant43": "Weather",
	"plant45": "Tag",
	"plant47": "Overview",
	"plant48": "Self-used Info",
	"plant49": "Today ",
	"project4": "Planned Self-used Rate",
	"plant_detail138": "Irradiation",
	"plant51": "Historical Production",
	"manage100": "Notices",
	"plant_alert33": "Sub-system",
	"plant_alert37": "No Influence",
	"user54": "You do not have permissions on O&M sector. Jump cannot be performed.",
	"user55": "Select at least 1 business sector",
	"plant_detail139": "Parameter Read&Write",
	"plant_detail140": "Command Name",
	"app12": "Top Up",
	"device32": "Applicable hardware version",
	"device_management32": "Last Command Record",
	"device_management33": "Select Command",
	"device_management34": "Timeout",
	"device_management35": "Current Version Info",
	"device_management36": "Last Upgrade Record",
	"device_management37": "Target Version",
	"device_management38": "Upgraded Time",
	"device_management39": "Upgrade State",
	"manage101": "Selected Sector(s)",
	"device33": "Applicable Model",
	"device34": "Upgradable Software Version",
	"device35": "COM Status",
	"device38": "Operation Records",
	"plant52": "Self-used",
	"plant53": "Feed-in",
	"plant54": "Production",
	"plant55": "Power Purchased",
	"plant56": "Feedback Time",
	"plant_alert41": "Please enter alert name",
	"plant_detail144": "Time-sharing Self-used Consumption",
	"plant_list20": "Peak Hour Rankings",
	"plant_list21": "Updated",
	"plant58": "Standard Coal Saved",
	"plant59": "Clear Filter",
	"plant61": "Read&Write Records",
	"plant62": "Linkage",
	"plant63": "Sub-device",
	"plant64": "Parent Device",
	"device39": "Applicable Product",
	"device40": "Package",
	"device41": "Set Upgrade Scope",
	"device43": "Select Sub-device Adding Method",
	"plant_delete8": "Sure to delete the offset?",
	"device44": "Applicable firmware version",
	"plant_detail147": "Sending",
	"plant_detail148": "No suitable gateway/logger is available",
	"plant_detail149": "Added",
	"plant_detail152": "Trees Planted",
	"plant_detail156": "Historical Production",
	"plant_detail157": "Currency",
	"plant_detail159": "Creation Date",
	"plant68": "Follow in Batch",
	"device45": "Device Upgrade",
	"plant_detail160": "Flow Chart",
	"plant_detail161": "Unknown",
	"device_management46": "Deleting other devices(except  gateway/logger) is not supported for now.",
	"device_record12": "CO₂ Emission Reduction",
	"device_record14": "Purpose",
	"device_management47": "Enter SN",
	"user58": "Server cannot be accessed for now. Please try again later.",
	"device_management49": "Adding oneself is not allowed",
	"device46": "① GPRS1 (AT+UPURL=47.88.6.171:30005,filename) #Original GPRS1, netty server-1st Generation",
	"device47": "② GPRS2 (AT+UPDATE=214028,10,http://198.11.174.215:30004/filepath,filename) #Original Generic Version of GPRS2&GPRS3, Generic HTTP File Server",
	"device48": "③ WIFI (AT+UPURL=http://198.11.174.215:30004/file_path_name) #Original WIFI, Generic HTTP File Server",
	"device49": "④ Ethernet (AT+UPDATE=214028,0,http://198.11.174.215:30004/,file_path_name) #Original Ethernet, Generic HTTP File Server",
	"device50": "⑤ GPRS21 (AT+UPDATE=214028,10,http://198.11.174.215:18021/,filename) #Original Special Version of GPRS2&GPRS3, Customizednginx Server",
	"device51": "⑥ CDMA (Not Available for now)",
	"device52": "① GPRS1 (AT+INVUPURL=47.88.6.171:21,power,QdTrQB7,/,filename) #Original Generic Version of GPRS1, Generic FTP File Server",
	"device53": "② GPRS2 (AT+UPDATE=214028,20,http://198.11.174.215:30004/filepath,filename) #Original Generic Version of GPRS2, Generic HTTP File Server",
	"device54": "③ GPRS3 (AT+FTPUPURL=47.88.6.171:21,power,QdTrQB7,/,filename) #Original GPRS3, Generic FTP File Server",
	"plant82": "All Products",
	"plant_alert45": "Alerting",
	"device_management50": "Product Name",
	"plant_detail162": "Following Status",
	"plant_detail163": "Online",
	"plant253": "Please Select System",
	"device55": "④ WIFI (AT+INVUPURL=http://198.11.174.215:30004/)  #Original WIFI, Generic HTTP File Server",
	"plant84": "Current operation is not supported for now",
	"all11": "Details",
	"plant85": "Grid-connected",
	"plant_alert46": "Influence",
	"plant_alert48": "Last Trigger Time",
	"plant_detail165": "Last Connection Time",
	"plant_detail166": "⑤ Ethernet (AT+UPDATE=214028,1,http://198.11.174.215:30004/,file_path_name)  #Original Ethernet, Generic HTTP File Server",
	"device56": "⑥ Generic FTP (AT+SFTPUPURL=47.88.6.171:21,power,QdTrQB7,/,file_name,2,crc) #Original Generic FTP, Generic FTP File Server",
	"device57": "⑦ Generic HTTP (AT+SUPDATE=214028,http://198.11.174.215:30004/file_path/,file_name,2,crc) #Original Generic HTTP, Generic HTTP File Server",
	"device58": "⑧ GPRS11 (AT+INVUPURL=47.88.6.171:30005,filename) #Original Special Version of GPRS1, netty server-1st Generation",
	"device59": "⑨ GPRS21 (AT+UPDATE=214028,20,http://198.11.174.215:18021/,filename) #Original Special Version of GPRS2, Customized nginx server",
	"device60": "⑩ CDMA",
	"device_management52": "The device is not activated yet. No further information is available.",
	"plant86": "Plant founder does not open the permissions.",
	"plant_alert51": "Protocol Alert",
	"plant87": "Undo in Batch",
	"plant88": "Incoming Parameters",
	"plant_detail168": "Succeeded",
	"plant_detail169": "Failed",
	"user61": "Timeout",
	"app14": "COM Status",
	"device61": "Firmware Name",
	"plant_alert52": "Alert Status",
	"plant91": "Customized Command",
	"plant92": "Unfollow",
	"plant93": "Add in Batch",
	"plant94": "Cancel Adding in Batch",
	"user65": "Failure",
	"device63": "The data logger firmware does not exist",
	"manage120": "This role is the default external business, which has user permissions. It has partial function permissions, which cannot be modified.",
	"plant103": "Normal",
	"plant104": "Minute",
	"device_management53": "No system added for now",
	"plant106": "Please enter incoming parameters",
	"plant107": "Illegal incoming parameters",
	"device64": "Please Enter Timeout",
	"plant108": "Please enter a positive integer greater than 10 and less than 30",
	"plant109": "Send Command",
	"plant111": "Coordinate",
	"plant112": "Edit Business",
	"plant_control1": "Upgrading",
	"plant_detail170": "Irradiation(Irradiance, Irradiation）",
	"device65": "Select Firmware",
	"user69": "Please enter username",
	"plant_list23": "Please enter a positive integer greater than 10 and less than 40",
	"device66": "Upgrade",
	"device67": "Please Upload Firmware Package",
	"device68": "Firmware Package Decryption",
	"device69": "Alert Status",
	"device70": "Notice: System will determine the upgrade result based on whether the selected version changed or not.",
	"device71": "Please enter applicable model",
	"device72": "Please Enter Firmware Name",
	"device73": "Firmware name already existed",
	"device74": "Please upload firmware limit to 2M（bin、hex、mot、img、upg、scre、raw are supported.）",
	"device76": "Please Select Applicable Products",
	"device77": "Please select correlated version info",
	"device79": "Firmware Details",
	"plant_detail177": "What is sub-device?",
	"plant_detail179": "Please Enter SN",
	"user70": "Phone number field cannot be blank",
	"user71": "E-mail field cannot be blank",
	"custorner2": "Please enter business name",
	"plant_detail181": "Edit Firmware Info",
	"plant_detail183": "Alert",
	"manage133": "Log Management",
	"device81": "Upload Firmware",
	"user72": "Download APP",
	"manage136": "No. of customized external roles has exceeded the upper limit. (Limited to 20)",
	"manage137": "No. of customized roles has exceeded the upper limit. (Limited to 20)",
	"manage138": "You can't access this interface, please contact the super administrator to open this permission",
	"plant_detail188": "Example: 100、-100、100.03、-100.03",
	"plant_detail189": "Accumulated production parameter will be added with the offset you input.",
	"plant_detail190": "If the calculation of accumulated production is set as \"Accumulated production summation uploaded by devices\", it will generate offset.",
	"plant_detail191": "Daily production parameter will be added with the offset you input. Meanwhile, both monthly and yearly production will be affected. If the accumulated production is calculated via the summation of daily production, it will be affected as well.",
	"plant_detail192": "Offset will take effect within 30 mins",
	"plant_detail193": "No signal means there is no device in the plant or no data are sent to the system",
	"report2": "Obtain from plant list",
	"report3": "Obtain from device list",
	"report4": "Permission denied. Please contact super admin.",
	"report5": "Enter Inverter SN",
	"plant113": "Please enter plant name",
	"report6": "Enter Meter SN",
	"app15": "Notice: For a better visual experience, it is recommended to use a device with a length-width ratio of 16:9 and a resolution of more than 1080P to switch to full screen mode.",
	"plant_detail195": "The device has been added to the current plant, do not add it repeatedly",
	"plant_detail196": "The upgrade instruction format referring to the firmware version of the current data logger is not entered.",
	"report7": "Report object field cannot be blank",
	"device83": "Gateway not accessed yet. No entry is required.",
	"manage140": "API Entry. Uneditable.",
	"manage141": "API Entry. Unable to delete.",
	"manage142": "External Relation and Role",
	"report8": "Query",
	"manage143": "Check User List",
	"manage144": "Check External Role List",
	"manage145": "Device Import",
	"manage146": "Device Deletion",
	"manage147": "New Business",
	"plant_detail197": "The offset you just entered is the same with that of current date. Please enter a different parameter.",
	"plant_alert53": "Alerting status means system receives an alert recently",
	"plant_detail198": "Example: 100、-100、100.03、-100.03. If you want to add 100kWh offset for 2019/1/1, please enter 100. ",
	"device85": "Please upload a zip file",
	"device86": "Notice：update the original summary table file？",
	"device87": "Summary table file was uploaded successfully.",
	"device88": "Summary table file cannot be empty",
	"device_management54": "Configuration",
	"plant_detail199": "Supported Device: Module. Please make sure devices have been added to the plant, then you can edit system layout.",
	"device89": "Adaptation",
	"device90": "Recommended",
	"device91": "Imported component layout file will quickly match the layout information of all components in the plant. Please make sure that the component SN  in the file is in consistent with the existing component SN in the plant.",
	"device_management57": "Importing layout file will quickly match the layout info of existing devices in plants.",
	"device_management58": "Step 1: Please make sure all module SNs have been added.",
	"manage150": "Why the rules do NOT take effect immediately?",
	"user75": "Please check the following circumstances, which will take effect within 12 hours at the latest.",
	"device92": "Import Summary table file",
	"device93": "Import configuration file",
	"manage152": "Delete the role of receiver",
	"manage153": "The external role of receiver's business unit is deleted by the authorized party",
	"manage154": "Modify the role of receiver",
	"manage155": "The external role of receiver's business unit is modified by the authorized party",
	"manage156": "Internal Member",
	"device94": "Import Summary table file",
	"plant116": "Click here to edit system layout",
	"plant118": "Authorize in Batch",
	"plant119": "Restore",
	"plant120": "Clear",
	"user76": "Log In",
	"plant122": "Cancel plant authorization of receiver",
	"plant123": "Cancel plant authorization of receiver's business unit ",
	"device95": "Clear",
	"plant124": "Delete plants visible to receiver",
	"plant125": "Create plants visible to receiver",
	"plant_alert54": "Create a user and designated as receiver of alert message",
	"manage163": "Default rules are used to set alert grade and influence grade visible to different users, which can also set alert trigger logic. Please set special requirements at \"Special Rules\". ",
	"manage164": "Special rules are used to receive alert messages which cannot be received through default rules. Each business can set 10 special rules at max.. ",
	"manage165": "Each business unit can set 10 special rules at max.",
	"manage166": "Sure to delete this rule? After the deletion, this alert will be received according to default rules.",
	"manage167": "Receive? Receive Channel:",
	"manage168": "If you select \"On\", the message will be received automatically.",
	"plant126": "Select at least 1 member",
	"plant_alert55": "Trigger times field cannot be blank",
	"plant_alert56": "Please enter alert name/ID",
	"device_management59": "Year",
	"device_management60": "More",
	"device_management61": "Refresh",
	"device_management62": "Send",
	"device_management65": "Edit",
	"device_management67": "Device Library Log",
	"all12": "Save",
	"manage171": "Member Details",
	"all13": "Cancel",
	"plant129": "Tags Belonged to",
	"plant130": "Consumption History",
	"all14": "Delete",
	"plant131": "Yield Info",
	"app16": "Feed-in Tariff",
	"plant132": "Name",
	"app17": "Search",
	"plant134": "Working Company",
	"all15": "Select All",
	"device_management68": "Day",
	"device_management69": "Command Type",
	"device_management70": "Week",
	"device_management71": "Month",
	"device_management72": "Total",
	"plant_detail201": "Updated",
	"manage177": "Edit User",
	"plant_detail204": "Please check for detailed reasons.",
	"plant_detail205": "This alert has been set as Special Rule.",
	"plant_detail206": "System Info",
	"plant135": "Sub-system Name",
	"plant136": "Sub-system Type",
	"plant_detail207": "Plant Settings",
	"plant_detail208": "Data Source",
	"plant_detail209": "Current Temp",
	"plant_detail210": "Daily Irradiation",
	"plant_detail211": "Daily PR",
	"plant_detail212": "Peak Hours",
	"plant_detail213": "Peak Hours this Month",
	"plant137": "Monthly Irradiation",
	"plant_detail214": "Monthly PR",
	"plant_detail215": "Daily Temp",
	"plant_detail216": "Daily Weather",
	"plant_detail217": "Peak Hours this Year",
	"plant_detail218": "Yearly Irradiation",
	"plant_detail219": "Yearly PR",
	"plant_detail220": "Plant Area",
	"plant139": "Name/Location",
	"plant_detail221": "Data Type",
	"plant_detail222": "Total Peak Hours",
	"plant_detail223": "Total PR",
	"plant_detail224": "Total Irradiation",
	"plant140": "Production",
	"plant141": "Consumption",
	"plant142": "Grid",
	"plant143": "Inverter",
	"plant144": "Types",
	"plant146": "Offline",
	"plant148": "Parent Device Type",
	"plant_alert57": "Alert",
	"plant149": "Meter",
	"plant150": "Module",
	"plant151": "Weather Station",
	"plant_detail226": "Logger",
	"plant_detail227": "Current Weather",
	"device_management73": "Parent Device SN",
	"plant153": "Meter Configuration",
	"plant_detail228": "Sub-device List",
	"plant_detail230": "Add a New Sub-system",
	"plant158": "Edit Tags",
	"plant159": "Add a Tag",
	"plant161": "Edit Sub-system",
	"plant163": "Summary",
	"plant166": "Sunrise",
	"app18": "Frequently Used",
	"app19": "Calculation of accumulated production",
	"record11": "Accumulated production summation uploaded by devices",
	"plant_detail231": "Daily production summation",
	"plant_detail232": "Sunset",
	"plant_detail233": "Static",
	"app20": "Report service",
	"app21": "Resolution",
	"report9": "Period",
	"report10": "Objects",
	"report11": "Select Plants",
	"report12": "Select inverter",
	"report13": "Fields",
	"report14": "Select Fields",
	"report15": "Parameters",
	"report16": "Select Parameters",
	"app22": "Single",
	"plant167": "SN",
	"plant168": "Reports from multiple plants",
	"report17": "Select report object",
	"app23": "Multiple",
	"fullscreen4": "Min",
	"app24": "Day",
	"app25": "Month",
	"app26": "Display",
	"report18": "Device Data Source",
	"app27": "Please Enter Field Name",
	"plant_detail234": "Please Select Date to Check the Offset",
	"app28": "Please Select Report Parameter",
	"report19": "Please Enter Parameter Name",
	"fullscreen5": "Display List",
	"app29": "O&M System (Default)",
	"fullscreen6": "System Preset",
	"device_management74": "Total Daily Positive Energy",
	"device_management75": "Total Daily Negative Energy",
	"device_management76": "Total Monthly Positive Energy",
	"device_management77": "Total Monthly Negative Energy",
	"device_management78": "Peak Hours Today",
	"device_management79": "Configuration Management",
	"device96": "Configuration Info",
	"device97": "COM Mode",
	"device98": "Configuration Mode",
	"device99": "Network Mode",
	"plant_detail235": "Energy Purchase",
	"device100": "Auto",
	"device101": "Manual",
	"device102": "Gateway SN",
	"device103": "Model",
	"device104": "Hardware Version",
	"device105": "Firmware Version(factory setting)",
	"device106": "COM Mode",
	"device107": "Configuration Mode",
	"device108": "Network Mode",
	"device109": "Configuration Info Entry",
	"user81": "Device Password",
	"device_management80": "Download",
	"device110": "Edit Configuration Info",
	"device111": "SN template",
	"device112": "please upload the data logger SN file",
	"device113": "Status",
	"plant_detail236": "Parent Device Status",
	"plant_detail237": "Calculation of accumulated electricity",
	"plant169": "Layout",
	"app30": "Full Screen ",
	"app31": "Exit",
	"device114": "Configuration list",
	"device115": "State Grid poverty alleviation",
	"device116": "logger list",
	"device117": "Please enter logger SN",
	"device118": "Power generation account number",
	"device119": "Firmware status",
	"device120": "Check poverty alleviation logger",
	"device121": "Configuration File",
	"device122": "Point table file",
	"device123": "Certificate",
	"device124": "Uploaded",
	"device125": "Not uploaded",
	"device126": "Successfully adapted",
	"plant_list24": "Component List",
	"manage188": "String/No.",
	"manage189": "Click to download imported file template",
	"manage190": "Successful Import.",
	"manage191": "Import Failure",
	"manage192": "Message",
	"manage193": "Default Rules",
	"manage194": "Special Rules",
	"manage195": "Receive?",
	"manage196": "On",
	"manage197": "Off",
	"manage198": "APP Push",
	"manage199": "Off",
	"manage200": "On",
	"manage201": "Trigger Times",
	"manage202": "Receiver",
	"manage203": "E-mail",
	"manage204": "SMS",
	"manage205": "Phone Voice",
	"plant_detail240": "APP Push",
	"plant_detail241": "Grid Level 2 Underfrequency Value",
	"plant_detail242": "Message",
	"device_management81": "Device Type",
	"plant_alert58": "Add alert",
	"manage206": "Free trial. ",
	"manage207": "Edit Special Rules",
	"manage208": "Add Special Rules",
	"manage209": "Receiving Logic",
	"manage210": "Alert",
	"manage211": "Message Sending",
	"manage212": "Way",
	"manage213": "Charging Method",
	"manage214": "Surplus",
	"manage215": "Device",
	"manage216": "Add New Special Rules",
	"manage217": "Alert Management",
	"plant172": "Plants",
	"device127": "Firmware Version",
	"device128": "Current",
	"device_management82": "Logger",
	"device_management83": "Inverter",
	"plant_list25": "Total",
	"fullscreen7": "Total Production",
	"plant_list26": "Daily Production",
	"plant_list27": "Monthly Production",
	"device_management84": "Combiner Box",
	"plant_list28": "Yearly Production",
	"device_management85": "Weather Station",
	"device_management86": "Meter",
	"plant_detail243": "Air Conditioner",
	"plant_detail244": "Harmonic Meter",
	"plant_detail245": "Water&Air Quality Monitoring",
	"plant_detail246": "Smart Home",
	"plant_detail247": "Real-time",
	"plant_detail248": "Operation",
	"plant_list29": "Total Feed-in Energy",
	"plant_list30": "Total Energy Purchased",
	"plant_list31": "Daily Grid Feed-in",
	"plant_list32": "Daily Energy Purchased",
	"plant_list33": "Monthly Grid Feed-in",
	"plant_list34": "Monthly Energy Purchased",
	"plant_list35": "Yearly Grid Feed-in",
	"plant_list36": "Yearly Energy Purchased",
	"plant_list37": "Total Consumption",
	"plant_list38": "Daily Consumption",
	"plant_list39": "Monthly Consumption",
	"plant_list40": "Yearly Consumption",
	"plant_detail249": "Others",
	"plant_detail250": "Production",
	"plant_detail251": "Selected",
	"plant_detail252": "Selected",
	"plant174": "Grid",
	"plant175": "Consumption",
	"plant_detail255": "SN",
	"plant_detail256": "Language",
	"plant_alert60": "Alert",
	"plant_detail257": "Read",
	"device_management87": "Module",
	"manage221": "Province",
	"manage222": "City",
	"manage223": "Password",
	"plant_alert61": "Failures",
	"plant_alert62": "Warnings",
	"plant176": "Total Plants",
	"plant177": "Installed Capacity",
	"plant_detail261": "Capacity",
	"creat_plant7": "Plant Type",
	"creat_plant8": "Owner Info",
	"creat_plant10": "System Type",
	"creat_plant11": "Ground Mounted ",
	"creat_plant12": "Residential Rooftop",
	"creat_plant13": "Commercial Rooftop",
	"creat_plant14": "Industrial Rooftop",
	"creat_plant15": "All on Grid",
	"creat_plant16": "Self-consumption",
	"creat_plant17": "Name",
	"creat_plant18": "Location",
	"creat_plant19": "Angle of Tilt",
	"creat_plant20": "Time Zone",
	"creat_plant21": "Azimuth",
	"device129": "Device Control",
	"plant_detail263": "Operator",
	"device_management88": "DTU",
	"device_management89": "Repeater",
	"device_management90": "Microinverter",
	"device_management91": "Current Version",
	"device_management92": "Please Select",
	"plant_list42": "Longitude",
	"plant_list43": "Latitude",
	"creat_plant24": "Address",
	"plant_list45": "Frequency",
	"creat_plant25": "Power Supply",
	"plant_list46": "Wind Speed",
	"plant_detail265": "Sub-device Adding: Manual-adding",
	"plant_detail266": "Sub-device Adding: Auto-adding",
	"plant_detail267": "Loaded",
	"plant_detail268": "Phone Number",
	"plant_detail269": "No Data for Now",
	"plant_detail270": "Dial Permission Has Been Banned",
	"plant_detail271": "Your Phone Does Not Have an Application \\n to Dial",
	"plant_detail272": "XX Not Installed",
	"plant_detail273": "District",
	"plant_detail274": "Successful configuration! The data will be uploaded within 10 minutes.",
	"plant_detail275": "Target Wifi",
	"plant270": "Return to XXPro",
	"manage227": "Please go to network setup interface\\r to change the WiFi network \\r then return to XXPro",
	"manage228": "Please Enter WiFi Account",
	"manage229": "WiFi wireless network password only supports \\\"English Letters(a-z, A-Z)\\\", \\\"arabic numbers(0-9)\\\". \\\"Space\\\", \\\"Chinese\\\", and special characters are not supported.",
	"manage230": "Pull down to reload",
	"manage231": "Release to reload",
	"manage232": "Reloading...",
	"manage233": "Pull up to reload",
	"manage234": "Release to reload",
	"manage235": "Loading...",
	"manage236": "Loaded",
	"plant_list47": "Total Production",
	"app32": "Updated Time",
	"plant180": "Off",
	"plant_control2": "Upgrade Records",
	"plant_alert63": "Alerting ",
	"device130": "Operation Type",
	"device131": "Operation Time",
	"device132": "Operating",
	"device133": "Operation Status",
	"device136": "XX Page",
	"plant185": "XX Page",
	"plant_detail279": "Fail to get the computer location, switch to the country view where the computer is!",
	"plant186": "View",
	"plant187": "Operation Type",
	"plant188": "Device Operation Log",
	"plant189": "Operation Status",
	"plant190": "Batch Import",
	"user84": "Password field cannot be blank",
	"plant192": "Tag",
	"plant_delete10": "Sure to delete the plant? Deletion will cause the loss of historical data. Be cautious!",
	"plant_control3": "Upgrade Start Time",
	"plant194": "Enter currency name",
	"plant195": "All Plant Tags",
	"user85": "Chrome58+, Firefox49+ are recommended",
	"plant_alert76": "Normal",
	"plant196": "No Devices",
	"plant198": "Add a new logger directly",
	"app33": "Demo",
	"device_management93": "Sent Time",
	"device_management94": "Command State",
	"device_management96": "Authorized external role field cannot be blank",
	"app34": "Record List",
	"diagnosis": "Diagnosis",
	"plant199": "Location",
	"creat_plant26": "The coordinate of current cellphone can not be obtained, so the appropriate map is not available. Please click on \"Please select the area\" to determine the location of the plant.",
	"creat_plant27": "Please select the area",
	"creat_plant28": "Please notice",
	"creat_plant29": "Map",
	"creat_plant30": "Please select the longitude line",
	"creat_plant31": "Please select the latitude line",
	"creat_plant32": "Degree (°)",
	"creat_plant33": "Min (′)",
	"creat_plant34": "Sec (″)",
	"creat_plant35": "E",
	"creat_plant36": "W",
	"creat_plant37": "S",
	"creat_plant38": "N",
	"creat_plant39": "Commissioning",
	"creat_plant40": "Accessing",
	"manage242": "E-mail already exists. If you want to add the user or authorize a plant to the user, please go to \"Search for System-wide Users\" and enter the E-mail.",
	"homepage1": "Homepage",
	"creat_plant43": "Help",
	"user86": "XX Platform-User Version",
	"user87": "XX Platform (User Version) is designed for PV power plant users. It achieves full-day surveillance of PV power plant running situation and power generation benefits, which secures users’ properties.",
	"user88": "Go to XX",
	"user89": "XXPro Platform-Business Version",
	"user90": "XXPro Platform (Business Version) is designed for different businesses who provide various services. It offers different services for different business sectors. Furthermore, it meets complex scenarios and requirements, which also ensures power generation benefits and secures users’ properties.",
	"user91": "Go to XXPro",
	"user92": "Business",
	"user93": "Network unavaliable",
	"user94": "My applications",
	"device_record17": "Inverter data summation (SOC is calculated on average)",
	"plant201": "Battery (Battery Power, Battery Status, Energy Charged, Energy Discharged, SOC)",
	"device138": "Target device has not added to any system yet",
	"device139": "Go",
	"device140": "Battery Charge",
	"device141": "Battery Discharge",
	"device_management97": "Now",
	"plant_alert77": "Now means updated time. Alerting status means system receives an alert recently",
	"plant_list49": "SOC",
	"plant273": "Status",
	"plant_list50": "Total Energy Discharged",
	"plant_list51": "Offset",
	"plant_list52": "Yearly Energy Discharged",
	"plant_list53": "Monthly Energy Discharged",
	"plant_list54": "Daily Energy Discharged",
	"plant_list55": "Accumulated production offset",
	"plant_list56": "Daily production offset",
	"plant_list57": "Total Energy Charged",
	"plant_list58": "Yearly Energy Charged",
	"plant_list59": "Monthly Energy Charged",
	"plant_list60": "Daily Energy Charged",
	"plant202": "Electricity Purchasing",
	"user95": "No more message",
	"app35": "Report",
	"app36": "Charge",
	"app37": "Battery",
	"plant_detail283": "Unit Price",
	"plant_detail284": "Energy Storage System",
	"plant_detail285": "Permissions to XX is denied. Unable to jump.",
	"plant_detail286": "Local album can be set as plant picture under your permission.",
	"plant_detail287": "No result found, create an account for the business?",
	"plant_detail288": "Allow",
	"plant_detail289": "Not Allow",
	"plant_detail290": "Scan gateway/logger SN to obtain other information",
	"report22": "Export",
	"plant_detail291": "“XX\" wants to access your camera",
	"plant_detail292": "For Easy Retrieval of Plant Loc Information",
	"plant_detail293": "Allow“XX“ to access your location when using the application?",
	"plant_detail294": "\"Notice\" includes message, icon and voice. Go to \"Settings\" to set.",
	"plant_detail295": "“XX”wants to send you notification messages ",
	"user96": "Terms of Service",
	"user97": "Password",
	"report23": "Display parameter field cannot be blank",
	"report24": "Return out of bounds",
	"report25": "Select meter",
	"report26": "Loading",
	"plant_detail296": "Manual-adding",
	"plant_detail297": "Auto-adding (Recommended)",
	"plant203": "Plant report",
	"plant204": "Sub-device Adding:",
	"plant_detail298": "Initial: A~Z",
	"plant_detail299": "Initial: Z~A",
	"plant_detail302": "Ascending order according to daily production",
	"plant_detail303": "Descending order according to daily production",
	"plant_detail304": "Ascending order according to peak hours yesterday",
	"plant_detail305": "Descending order according to peak hours yesterday",
	"plant_detail306": "Updated time from near to far",
	"plant_detail307": "Updated time from far to near",
	"plant205": "Sort",
	"plant206": "Filter",
	"plant207": "Following Status",
	"plant_list61": "Min.",
	"plant_list62": "Max.",
	"plant208": "Device Status",
	"plant209": "Joined",
	"plant210": "Not Joined",
	"plant211": "Please Add",
	"user98": "Modify Password",
	"user99": "Old password field cannot be blank",
	"plant212": "Please enter a gateway/logger SN belongs to the plant first, system will count data according to gateway/logger and its sub-system. Non-required field. You can operate in the Plant Details.\nIf your gateway device is used only for one plant, auto-adding is recommended. System will automatically add sub-devices to the plant based on the connection between the gateway device and the sub-device.\nIf your gateway device is used for multiple plants, manual-adding is recommended. You can select the suitable sub-devices based on the actual usage of sub-device. \\rNotice: Make sure that sub-devices (such as inverters, meters, modules, and etc.) are powered on and communicate with the gateway device (such as loggers) properly. If you have not found the target sub-device, please refresh the list of sub-devices.",
	"manage243": "Please do the following operations",
	"manage244": "Please Enter Command",
	"manage245": "Create XX",
	"manage246": "Delete External Role",
	"manage247": "Edit External Role",
	"manage248": "Delete User",
	"manage250": "Add a New User",
	"manage251": "Check User Details",
	"manage252": "Delete Business",
	"manage253": "Add a New Business",
	"manage254": "Check Business Details",
	"manage255": "Check Business List",
	"manage257": "Check Member Details",
	"manage258": "Check About Business",
	"manage259": "Edit Firmware Info",
	"plant_alert78": "Check Alert List",
	"plant_detail308": "No firmware available. Please upload.",
	"plant_detail309": "Go to Upload",
	"user100": "Please enter name",
	"user101": "Baidu Map",
	"user102": "Amap Map",
	"user103": "Google Map",
	"user104": "Apple Map",
	"user105": "Please select the map",
	"user106": "History",
	"device142": "Enter Module SN",
	"device143": "Enter Weather Station SN",
	"device144": "Enter Logger SN",
	"plant213": "New Gateway/Logger List",
	"user108": "Camera is unavailable",
	"user109": "Turn on Flashlight",
	"user110": "Add a Device and Sub-system",
	"user111": "Navigation",
	"user112": "Business",
	"plant214": "Please Enter Device SN",
	"plant215": "Gateway/Logger SN",
	"plant_delete11": "If the gateway device you selected has sub-devices, these sub-devices will be deleted synchronously. Sure to delete the gateway/logger?",
	"plant216": "Upload",
	"plant_detail310": "No suitable navigation softwares were found. It is recommended to install Baidu Map, Amap and Google Map.",
	"plant_detail311": "Enter SN",
	"plant_detail312": "Limit to n parameter units",
	"plant_detail313": "Temperature Range",
	"plant_detail314": "Updated",
	"plant_detail315": "Selected Parameters cannot exceed X",
	"plant_detail316": "XX systems",
	"plant_alert79": "Current Alerts",
	"plant_detail317": "Discharge",
	"plant_detail318": "Device has not added to any system yet",
	"plant_alert80": "Search Devices/Alerts in Plant",
	"plant_delete12": "Sure to delete the plant? Deletion will cause the loss of historical data. Be cautious!",
	"manage261": "Contact number field is blank",
	"plant217": "Location service is disabled for now. Please set the location service in the control panel/system settings, and allow the access to location service.",
	"plant_detail319": "Adding a new sub-device cannot be operated",
	"plant_detail320": "Only sub-device is added via manual-adding can be added again.",
	"plant_detail321": "Current Adding Method",
	"plant_detail322": "Sub-device Adding",
	"plant_detail324": "Sub-device Adding: Auto-adding (Recommended)",
	"plant_detail325": "You can do the following operations on gateway/logger XX.",
	"plant_detail326": "No gateway/logger is available",
	"plant_detail327": "Replace Existing Gateway Devices: Off",
	"plant_detail328": "Replace Existing Gateway Devices: On",
	"plant_detail329": "Replace Existing Gateway Devices",
	"plant_detail330": "Add a New Device Directly",
	"plant_detail331": "If your gateway/logger is embedded module, please contact your device vendor for accurate SN sticking position.",
	"plant_detail332": "SN is usually pasted to the enclosure of gateway/logger. Here are common SN styles. Scan QR code/bar code or input the number manully to add the device.",
	"plant_detail333": "SN Location",
	"plant_detail334": "Turning on a flashlight requires the right to turn on the camera first.",
	"plant_detail335": "Enter Device SN",
	"plant_detail336": "Purpose: Replace Existing Gateway Devices",
	"plant_detail337": "Purpose: Add a New Device Directly",
	"plant_detail338": "QR code is empty. It is recommended to input SN manually.",
	"plant_detail339": "Scan SN",
	"plant_detail340": "Scan Bar Code/QR Code",
	"plant_detail341": "Logger SN",
	"plant_detail342": "Certificate file cannot be empty",
	"device145": "Point table file cannot be empty",
	"device146": "Successfully adapted",
	"device147": "Please upload Summary table file first",
	"device148": "Upload configuration file",
	"device149": "Please upload configuration file",
	"device150": "XX File successfully adapted ",
	"device151": "The following files cover the old version, XX in total",
	"device152": "The name of the file you uploaded is XX, the name is not standardized, the upload failed. Please re-name the upload.",
	"device153": "Upload a total of XX files",
	"device154": "Please note that all file formats uploaded must be zip files, XX not in .zip files.",
	"plant_detail343": "Add a New Sub-device",
	"plant218": "0~90°",
	"plant219": "Edit",
	"plant220": "0~360°",
	"plant221": "Physical Layout",
	"plant222": "Electrical Layout",
	"plant223": "0~100%",
	"user114": "Me",
	"user115": "Import",
	"app38": "Preview",
	"app39": "Applications",
	"user116": "Phone Number Does Not Exist",
	"app40": "Upload reference picture",
	"plant224": "File Template",
	"plant225": "Module SN",
	"plant226": "Coordinate X",
	"plant227": "Coordinate Y",
	"app41": "E-mail Does Not Exist",
	"user117": "Edit Business Name",
	"manage262": "Add a New Business Name",
	"manage263": "Business Name List",
	"app42": "Importing",
	"app43": "Hide",
	"app44": "Replace",
	"plant228": "Exit",
	"plant229": "Maintenance Record",
	"plant230": "Please enter maintenance record",
	"plant231": "Add a new record",
	"plant232": "Name",
	"plant233": "Maintainer",
	"plant234": "Time",
	"plant235": "E-mail",
	"plant236": "Object",
	"app45": "n Names",
	"app46": "Insurance",
	"app47": "System Type",
	"plant237": "System",
	"app48": "Object Type",
	"manage264": "Edit",
	"plant238": "Detail",
	"app49": "Note",
	"user118": "Select Business Area",
	"user119": "Select Business Sector",
	"user120": "Enter Business Name",
	"user121": "Quit？",
	"user122": "Select Country/Code",
	"user123": "Details",
	"user130": "XX SMS at max. Limit to Chinese Phone Number",
	"manage265": "Linkage",
	"manage279": "E-mail",
	"manage280": "SMS",
	"manage281": "Phone Voice",
	"manage284": "Search for System-wide Users",
	"manage285": "Phone Number",
	"manage288": "Click here to authorize users",
	"manage289": "Click here to authorize internal members",
	"manage290": "No Users",
	"manage291": "No Businesses",
	"manage292": "No Internal Members",
	"manage293": "Please select the way to authorize business units",
	"manage294": "Business name field cannot be blank",
	"manage295": "Sector",
	"manage296": "Please enter member name",
	"manage297": "Categories",
	"manage298": "Sure to clear all tags?",
	"manage299": "Tag name field cannot be blank",
	"manage303": "Login E-mail",
	"manage304": "Login Username",
	"manage306": "Login Phone Number",
	"manage307": "O&M Personnel",
	"plant243": "Select Existing Businesses",
	"plant244": "Quality Control",
	"plant245": "Time zone field cannot be blank",
	"plant246": "Currency  field cannot be blank",
	"plant247": "Thunderstorm",
	"plant248": "Click here to authorize business units",
	"user132": "Login Failure",
	"user133": "Registration Failure",
	"plant249": "Select Existing Users",
	"manage312": "O&M Director",
	"manage321": "Agency",
	"manage322": "Owner",
	"user135": "Country/Code",
	"user138": "Forget Password？",
	"plant250": "Step 2: XX export all module info.",
	"plant251": "Step 3: Enter layout info in the xls file.",
	"plant252": "How to fill out layout info?",
	"plant_detail344": "Step 4: Import xls file.",
	"plant_detail345": "You can",
	"plant_detail346": "Example",
	"plant_detail347": "1. Coordinate (X, Y) only supports positive integer.",
	"plant_detail348": "2. Coordinate X and coordinate Y cannot be the same. [e.g. Coordinates (1,1) is now allowed.] ",
	"plant_detail349": "3. String and No. info are non-required field. If you fill out these info, please make sure the No. corresponding to the same string starts from 1 and is continuous.",
	"plant_detail350": "Step XX",
	"plant_detail351": "Export all module info",
	"plant_detail352": "Please select sub-device",
	"plant_detail353": "Please Select Authorization Method",
	"plant_detail354": "Back Home",
	"manage324": "Check System Layout",
	"task1": "Bulk Task",
	"task2": "Please enter task name",
	"task3": "Task Type",
	"task4": "Task Status",
	"task5": "To Be Published",
	"task6": "Executing",
	"task7": "Finished",
	"task8": "Task Name",
	"task9": "Task Type",
	"task10": "Task Status",
	"task11": "Device No.",
	"task12": "No. of Success",
	"task13": "No. of Failure",
	"task14": "Sure to delete the task？",
	"task15": "Task has been published, which cannot be deleted.",
	"task16": "Task has been published, which cannot be edited.",
	"task17": "Create Task",
	"task18": "Task Content",
	"task19": "Customized  Content",
	"task20": "Task Time",
	"task21": "Starting Time",
	"task22": "Timeout",
	"task23": "Task Scope",
	"task24": "Filter",
	"task25": "Specified Device",
	"task26": "Specified Condition",
	"task27": "Condition Rule",
	"task28": "Add Condition",
	"task29": "Parameter",
	"task30": "Value",
	"task31": "Upload: 500. No. of Failure: 100.",
	"task32": "Back to modify",
	"task33": "Skip and publish",
	"task34": "Upload: 500 SNs, 100 of which do not exist. Sure to continue?",
	"task35": "Edit Task",
	"task36": "To be sent",
	"task37": "Terminate",
	"task38": "Parse Result",
	"task39": "Reason of Failure",
	"task40": "Send Again",
	"task41": "Send Again (Batch)",
	"task42": "Terminate (Batch)",
	"task43": "Sure to terminate the task?",
	"task44": "Only task to be sent can be terminated.",
	"task45": "Sure to send again?",
	"task46": "Only failed and terminated task can be sent again.",
	"task47": "Selected Device: 100. 35 device tasks (Device Status: Activated, Current Status: Failure/Terminate) can be sent again. Sure to send now? ",
	"task48": "Only device task (Device Status: Unactivated, Command Status: Failure/Terminate) can be sent again. No suitable tasks for now.",
	"task49": "Only upgrade task (To be sent/Upgrading) can be terminated.",
	"task50": "Only device task (Device Status: Unactivated, Upgrade Status: To be sent/Upgrading) can be terminated. No suitable tasks for now.",
	"task51": "Selected Device: 100. 35 device tasks (Delivery Status: To be sent/Upgrading) can be terminated. Sure to terminate now? ",
	"task52": "Selected Device: 100. 35 device tasks (Device Status: Activated, Upgrade Status: Failure/Terminate) can be sent again. Sure to send now? ",
	"task53": "Only device task (Device Status: Unactivated, Upgrade Status: Failure/Terminate) can be sent again. No suitable tasks for now.",
	"task54": "Only device upgrade task (Upgrade Status: Failure/Terminate) can be sent again. ",
	"task55": "Control task is operating, which cannot be terminated.",
	"task56": "Sure to terminate in batch?",
	"task57": "Check Bulk Task List",
	"task58": "Delete Task",
	"task59": "Send task agian",
	"task60": "Task Details",
	"task61": "Terminate task",
	"task62": "About task",
	"task63": "Download List",
	"task64": "Command State",
	"task65": "Conflicting Command",
	"task66": "Command Failure",
	"task67": "Parsing Failure ",
	"task68": "Product Type Error",
	"task69": "System Error",
	"task70": "Conflicting Command: Other command is being executed. Please try later.",
	"task71": "Command Failure: Command cannot be sent. Please check network and try later.",
	"task72": "Parsing Failure: Command sent, but device does not respond or response does not match the expectations. Please check actual device data.",
	"task73": "Product Type Error. Command cannot be sent.",
	"task74": "No. of SN exceeds upper limit. (Upper limit: 200)",
	"task75": "Non-standby Task",
	"task76": "Task Not Exist",
	"task77": "Bad Network. Please try again later.",
	"task78": "during upgrade",
	"task79": "Firmware Package",
	"task80": "Terminated",
	"task81": "Beyond the limit",
	"task82": "System Error：Instruction cannot be sent",
	"task83": "Didn't reach the task start time yet, is it sure to resume sending?",
	"task84": "If the task start time is not reached yet, a total of 100 devices will be selected. 35 devices whose current status is \\\"terminated\\\" can be restored to \\\"send to be sent\\\". Is it determined to resume immediately?",
	"task85": "The task start time is not reached yet. Only the device task whose current status is \\\"terminated\\\" can be restored to \\\"sending to send\\\". Currently, there is no device task that can be restored.",
	"local1": "Device does not support local mode",
	"me1": "Customer Service",
	"me2": "Operation Manual",
	"user149": "Local Mode",
	"manage326": "Partner(s)",
	"manage327": "About Alert Shielding",
	"manage328": "Alert shielding is not available for APP. You can go to Management (Web Version) to set.",
	"manage329": "No Message",
	"manage330": "Turn off Flashlight",
	"manage331": "Please enter microinverter SN",
	"manage332": "Please enter combiner box SN",
	"manage333": "Please enter repeater SN",
	"manage334": "Please enter battery SN",
	"manage335": "Please enter DTU SN",
	"download1": "SOLARMAN Business",
	"download2": "One-stop O&M, After Service Management Software",
	"download3": "For Android",
	"download4": "For IOS",
	"plant_detail1": "Microinverter",
	"plant_detail2": "Combiner Box",
	"plant_detail3": "Repeater",
	"plant_detail4": "Battery",
	"plant_detail5": "DTU",
	"plant_detail6": "Daily Production (Theoretical)",
	"plant_detail7": "Monthly Production (Theoretical)",
	"plant_detail8": "Yearly Production (Theoretical)",
	"plant_detail9": "Daily CPR",
	"plant_detail10": "Monthly CPR",
	"plant_detail11": "Purchase",
	"plant_detail12": "Photo",
	"plant_detail13": "Click here to add photo",
	"plant_detail14": "Add Photo",
	"plant_detail15": "Supported Format: JPG/GIF/PNG/JPEG (Size limit to 2M)",
	"plant_detail16": "Upload Photo",
	"plant_detail17": "Title",
	"plant_detail18": "Description",
	"plant_detail19": "Sure to delete the photo?",
	"plant_detail20": "Up to 50 photos for each plant",
	"plant_detail21": "Production (Theoretical)",
	"plant_detail22": "Algorithm",
	"station1": "Virtual Weather Station",
	"fullscreen1": "Display Title",
	"role1": "Overview",
	"role2": "No data permission",
	"role3": "Data permission is subjected to plant data settings in Overview sector.",
	"device155": "Network Connected Now Is XX, Might Be Logger's WiFi, Switch to Normal Network",
	"device156": "Switch",
	"device157": "Do Not Switch",
	"device158": "Logger Connected to Network, Continue Configuration?",
	"device159": "Continue",
	"device160": "Why Need Access?",
	"device161": "Scanning QR Code Requires Access to Camera",
	"device162": "Understand and Agree",
	"device163": "Reject Authorizing",
	"device164": "No Camera Access, Back",
	"device165": "Give Access to System Interface",
	"device166": "Connect",
	"device167": "Quit",
	"creat_plant44": "Need Accurate Location Info to Build Plant",
	"creat_plant45": "No Locating Access, Back",
	"creat_plant46": "Locating Fail",
	"creat_plant47": "Locating Fail,Use Default",
	"creat_plant48": "Locating, Please Wait",
	"creat_plant49": "Locating, Please Wait",
	"member1": "Please enter Alias",
	"customer1": "Clue",
	"plant1": "Select System in Btach",
	"creat_plant51": "Invalid Uploading Files",
	"creat_plant52": "Loading, Please Wait…",
	"creat_plant53": "No Result ",
	"plant_detail371": "Firmware Upgrade",
	"plant_detail372": "Create",
	"plant_detail373": "View",
	"creat_plant54": "Fixed Payment Mortgage",
	"creat_plant55": "Fixed Basis Mortgage",
	"creat_plant56": "Creation Time",
	"creat_plant57": "Contact Number",
	"creat_plant58": "Authority",
	"creat_plant59": "Group",
	"creat_plant60": "Flat Rooftop",
	"creat_plant61": "Inclined Rooftop",
	"creat_plant62": "All",
	"plant257": "Search for System-wide Businesses",
	"all1": "Refresh",
	"all2": "Batch Operation",
	"all3": "File Type Error",
	"all4": "Please select a device",
	"role4": "This role is for O&M management personnel. Please clone the role first before modification.",
	"role5": "This role is for O&M personnel. Please clone the role first before modification.",
	"role6": "This role is for O&M agent personnel. Please clone the role first before modification.",
	"role7": "This external role is for your client. Please clone the role first before modification.",
	"role8": "This external role is for your business partner. Please clone the role first before modification.",
	"plant_detail23": "This plant was authorized by XX (Business unit).",
	"plant_detail24": "This plant was authorized by XX (User).",
	"plant_detail25": "Contact Address",
	"plant_detail26": "This plant has no module layout info. Please go to Business Web to edit.",
	"plant_detail27": "This plant has more than XX module(s). Please go to Business Web to check.",
	"plant_detail28": "Physics",
	"plant_detail29": "Click to go to Layout Details. Users can zoom in and out of Layout Detais here and check more data.",
	"report1": "Export",
	"message1": "More",
	"project1": "Planned Start Time",
	"project2": "Planned End Time",
	"project3": "Planned Day(s)",
	"plant_detail30": "Module data summation",
	"device1": "Add a Device",
	"device2": "Device Type",
	"report27": "Total",
	"report28": "Select at least one object",
	"device_management101": "Firmware Package",
	"device_management102": "Not Available",
	"app50": "Report Type",
	"device_management104": "Off-grid",
	"device_management106": "Account",
	"plant_detail378": "Date",
	"plant_detail379": "Time Period",
	"device200": "Product",
	"device201": "Add",
	"user150": "Confirm Password (At least 6 Characters)",
	"manage337": "Size Limit to XXMB",
	"manage338": "Please enter the number between XX (Hold 2 Digits)",
	"manage339": "Please fill in the form as required",
	"control38": "Back",
	"control39": "Import Template in Batch",
	"control40": "485 Device",
	"control41": "485 Device with Communication Address Variable ",
	"control42": "Command Object",
	"Networking1": "Network",
	"Networking2": "Start",
	"Networking4": "Object(s)",
	"Networking5": "Select",
	"Networking6": "Communication Relationship",
	"Networking7": "SN has not been activated yet, which cannot be networked. Please make sure the device is ready for power on, then connect to server and try again.",
	"Networking8": "Device does not support networking or does not require networking.",
	"Networking9": "Networking",
	"Networking10": "Networking! Please wait.",
	"Networking11": "Networked!  Please refresh communication relationship in 5-10 mins.",
	"Networking12": "Networking failure!  Please try again.",
	"Networking13": "Network Relationship",
	"Networking14": "Upload Network Relationship",
	"Networking15": "Record",
	"Networking16": "Status",
	"Networking17": "Time",
	"Networking18": "Type/SN",
	"role9": "Check Maintenance Record",
	"role10": "Delete Maintenance Record",
	"role11": "All Maintenance Records",
	"role12": "Maintenance Record(s) of My&Subordinate Dep.",
	"role13": "Maintenance Record(s) of My Dep.",
	"role14": "My Maintenance Records",
	"role15": "Add a New Dep./Member",
	"role16": "This default role has full permissions, which cannot be changed.",
	"role17": "This default role has partial permissions, which cannot be changed.",
	"plant_detail31": "Duplicate selection of algorithm is not allowed.",
	"plant_detail32": "Theoretical Energy (Include Theoretical Production)",
	"app1": "Instant Free",
	"app2": "Creation Time",
	"app3": "Name",
	"app4": "Sure to delete maintenance record?",
	"alert1": "Total XX Alert(s)",
	"alert2": "Device",
	"app5": "More",
	"app6": "XX devices",
	"alert3": "Alerting",
	"device3": "Device Offline",
	"device4": "Device Cost",
	"diagnosis1": "Diagnosis",
	"diagnosis2": "Report",
	"diagnosis3": "Type",
	"diagnosis4": "Objects",
	"diagnosis5": "Method",
	"diagnosis6": "Time",
	"diagnosis7": "Diagnosis Time: X2X. (Plant No.: X1X)",
	"diagnosis8": "Only the data for yesterday will be diagnosed. It is recommended to start the diagnosis in the morning.",
	"diagnosis9": "Select Objects",
	"diagnosis10": "Please select objects",
	"diagnosis11": "Easy for users to find out the problem of plant.",
	"diagnosis12": "Solution",
	"diagnosis13": "Last Diagnosis Time",
	"diagnosis14": "Preparing the data. Please start the diagnosis after 6:00 AM.",
	"diagnosis15": "Start",
	"diagnosis16": "Checking: XX",
	"diagnosis17": "Data Quality",
	"diagnosis18": "Production Quality",
	"diagnosis19": "Potential Risk",
	"diagnosis20": "Report is being generated. Please wait.",
	"diagnosis21": "Only the data for yesterday will be diagnosed.",
	"diagnosis22": "Duration",
	"diagnosis23": "Checking",
	"diagnosis24": "Done",
	"diagnosis25": "Generate Report",
	"diagnosis26": "Generating",
	"diagnosis27": "Done",
	"diagnosis28": "There is a problem with diagnosis. Please try it again ater.",
	"diagnosis29": "Plant: XX",
	"diagnosis30": "Select Again",
	"diagnosis31": "Leave",
	"diagnosis32": "Current plant cannot be diagnosed. Please click \\\"Slect Again\\\" to select another plant.",
	"diagnosis33": "Report for multi plants",
	"diagnosis34": "Report for single plant",
	"diagnosis35": "Please enter report name",
	"diagnosis36": "Duration",
	"diagnosis37": "Diagnose Again",
	"diagnosis38": "Level Definition",
	"diagnosis39": "Level XX",
	"diagnosis40": "No abnormal plants or failure devices were found.",
	"diagnosis41": "Plant might encounter a problem, which needs to be watched.",
	"diagnosis42": "Data quality is not sufficient, which cannot determine the plant status.",
	"diagnosis43": "Device failure, which will influence production.",
	"diagnosis44": "Potential risk was found.",
	"diagnosis45": "Phenomenon",
	"diagnosis46": "Data Source",
	"diagnosis47": "Knowledge Base",
	"diagnosis48": "Include",
	"diagnosis49": "Report Name",
	"diagnosis50": "Start Time",
	"diagnosis51": "Plant will be classified into Level A, B, C, D, E. Level D and Level E plant are considered to be abnormal plant, which need to be watched and handled.",
	"diagnosis52": "No. of Abnormal Plant",
	"diagnosis53": "X% of Total Plant",
	"diagnosis54": "Production Loss of Abnormal Plant",
	"diagnosis55": "X% of Total Production",
	"diagnosis56": "Plant Number of Different Levels",
	"diagnosis57": "Plant (Level XX)",
	"diagnosis58": "Unexecuted Plant",
	"diagnosis59": "Unexecuted plant means the plant cannot be diagnosed.",
	"diagnosis60": "Diagnosis Time: XX",
	"diagnosis61": "Notice",
	"diagnosis62": "Offline Diagosis",
	"diagnosis63": "Data Reliability",
	"diagnosis64": "For improving the accuracy of finding abnormal plant, it is recommended that the plant has at least one radiation data source (e.g. Weather Station) or the plant is located in the city which supports PV Production Benchmark Index.",
	"diagnosis65": "City Supports PV Production Benchmark Index",
	"diagnosis66": "Beijing",
	"diagnosis67": "Anhui",
	"diagnosis68": "Fujian",
	"diagnosis69": "Gansu",
	"diagnosis70": "Guangdong",
	"diagnosis71": "Guangxi",
	"diagnosis72": "Hebei",
	"diagnosis73": "Henan",
	"diagnosis74": "Heilongjiang",
	"diagnosis75": "Hubei",
	"diagnosis76": "Hunan",
	"diagnosis77": "Jilin",
	"diagnosis78": "Jiangsu",
	"diagnosis79": "Jiangxi",
	"diagnosis80": "Liaoning",
	"diagnosis81": "Inner Mongolia",
	"diagnosis82": "Ningxia",
	"diagnosis83": "Shandong",
	"diagnosis84": "Shanxi",
	"diagnosis85": "Shaanxi",
	"diagnosis86": "Shanghai",
	"diagnosis87": "Sichuan",
	"diagnosis88": "Tianjin",
	"diagnosis89": "Zhejiang",
	"diagnosis90": "Zhangzhou",
	"diagnosis91": "Lu'an",
	"diagnosis92": "Hefei",
	"diagnosis93": "Anqing",
	"diagnosis94": "Suzhou",
	"diagnosis95": "Huaibei",
	"diagnosis96": "Huainan",
	"diagnosis97": "Zhangzhou",
	"diagnosis98": "Wuhu",
	"diagnosis99": "Benbu",
	"diagnosis100": "Fuyang",
	"diagnosis101": "Ma On Shan",
	"diagnosis102": "Huangshan",
	"diagnosis103": "Sanming",
	"diagnosis104": "Nanping",
	"diagnosis105": "Xiamen",
	"diagnosis106": "Ningde",
	"diagnosis107": "Quanzhou",
	"diagnosis108": "Zhangzhou",
	"diagnosis109": "Longyan",
	"diagnosis110": "Lanzhou",
	"diagnosis111": "Jiuquan",
	"diagnosis112": "Dongguan",
	"diagnosis113": "Zhongshan",
	"diagnosis114": "Yunfu",
	"diagnosis115": "Foshan",
	"diagnosis116": "Guangzhou",
	"diagnosis117": "Jieyang",
	"diagnosis118": "Meizhou",
	"diagnosis119": "Shantou",
	"diagnosis120": "Heyuan",
	"diagnosis121": "Qingyuan",
	"diagnosis122": "Zhanjiang",
	"diagnosis123": "Maoming",
	"diagnosis124": "Shaoguan",
	"diagnosis125": "Nanning",
	"diagnosis126": "Baoding",
	"diagnosis127": "Tangshan",
	"diagnosis128": "Langfang",
	"diagnosis129": "Zhangjiakou",
	"diagnosis130": "Chengde",
	"diagnosis131": "Zhangzhou",
	"diagnosis132": "Shijiazhuang",
	"diagnosis133": "Qinhuangdao",
	"diagnosis134": "Hengshui",
	"diagnosis135": "Xingtai",
	"diagnosis136": "Handan",
	"diagnosis137": "Nanyang",
	"diagnosis138": "Zhoukou",
	"diagnosis139": "Shangqiu",
	"diagnosis140": "Anyang",
	"diagnosis141": "Pingdingshan",
	"diagnosis142": "Xinxiang",
	"diagnosis143": "Luoyang",
	"diagnosis144": "Luohe",
	"diagnosis145": "Xianning",
	"diagnosis146": "Jingzhou",
	"diagnosis147": "Fuyang",
	"diagnosis148": "Huanggang",
	"diagnosis149": "Bottom",
	"diagnosis150": "Yue Yang",
	"diagnosis151": "Changde",
	"diagnosis152": "Zhangjiajie",
	"diagnosis153": "Huaihua",
	"diagnosis154": "Yiyang",
	"diagnosis155": "Hengyang",
	"diagnosis156": "Shaoyang",
	"diagnosis157": "Zhangzhou",
	"diagnosis158": "Changsha",
	"diagnosis159": "Siping",
	"diagnosis160": "Matsubara",
	"diagnosis161": "Changchun",
	"diagnosis162": "Jiaozuo",
	"diagnosis163": "Zhengzhou",
	"diagnosis164": "Suihua",
	"diagnosis165": "Heihe",
	"diagnosis166": "Nanjing",
	"diagnosis167": "Nantong",
	"diagnosis168": "Suqian",
	"diagnosis169": "Changzhou",
	"diagnosis170": "Xuzhou",
	"diagnosis171": "Wuxi",
	"diagnosis172": "Taizhou",
	"diagnosis173": "Huai'an",
	"diagnosis174": "Yancheng",
	"diagnosis175": "Suzhou",
	"diagnosis176": "Lianyungang",
	"diagnosis177": "Zhenjiang",
	"diagnosis178": "Shangrao",
	"diagnosis179": "Jiujiang",
	"diagnosis180": "Ji'an",
	"diagnosis181": "Yichun",
	"diagnosis182": "Fuzhou",
	"diagnosis183": "Jingdezhen",
	"diagnosis184": "Ganzhou",
	"diagnosis185": "Yingtan",
	"diagnosis186": "Dandong",
	"diagnosis187": "Dalian",
	"diagnosis188": "Chaoyang",
	"diagnosis189": "Huludao",
	"diagnosis190": "Liaoyang",
	"diagnosis191": "Tieling",
	"diagnosis192": "Anshan",
	"diagnosis193": "Chifeng",
	"diagnosis194": "Zhongwei",
	"diagnosis195": "Dongying",
	"diagnosis196": "Linyi",
	"diagnosis197": "Weihai",
	"diagnosis198": "Texas",
	"diagnosis199": "sunshine",
	"diagnosis200": "Zaozhuang",
	"diagnosis201": "Taian",
	"diagnosis202": "Jinan",
	"diagnosis203": "Jining",
	"diagnosis204": "Zibo",
	"diagnosis205": "Binzhou",
	"diagnosis206": "Weifang",
	"diagnosis207": "Liaocheng",
	"diagnosis208": "Laiwu",
	"diagnosis209": "Heze",
	"diagnosis210": "Qingdao",
	"diagnosis211": "Linyi",
	"diagnosis212": "Lu Liang",
	"diagnosis213": "Datong",
	"diagnosis214": "Taiyuan",
	"diagnosis215": "Zhangzhou",
	"diagnosis216": "Jinzhong",
	"diagnosis217": "Jincheng",
	"diagnosis218": "Zhangzhou",
	"diagnosis219": "Yuncheng",
	"diagnosis220": "Changzhi",
	"diagnosis221": "Yangquan",
	"diagnosis222": "Xianyang",
	"diagnosis223": "Baoji",
	"diagnosis224": "Yulin",
	"diagnosis225": "Weinan",
	"diagnosis226": "Xi'an",
	"diagnosis227": "Shanghai",
	"diagnosis228": "Panzhihua",
	"diagnosis229": "Tianjin",
	"diagnosis230": "Lishui",
	"diagnosis231": "Taizhou",
	"diagnosis232": "Jiaxing",
	"diagnosis233": "Ningbo",
	"diagnosis234": "Hangzhou",
	"diagnosis235": "Wenzhou",
	"diagnosis236": "Huzhou",
	"diagnosis237": "Shaoxing",
	"diagnosis238": "Zhoushan",
	"diagnosis239": "Zhangzhou",
	"diagnosis240": "Jinhua",
	"diagnosis241": "Data quality qualified",
	"diagnosis242": "Data quality not qualified",
	"diagnosis243": "Influence production quality inspection&safety inspection ",
	"diagnosis244": "Production is normal and no abnormal device found",
	"diagnosis245": "Production is low and device is abnormal",
	"diagnosis246": "Production quality inspection will not be carried out.",
	"diagnosis247": "Production quality needs to be watched.",
	"diagnosis248": "Safety inspection qualified",
	"diagnosis249": "Potential risk was found.",
	"diagnosis250": "Safety inspection will not be carried out.",
	"diagnosis251": "Pass",
	"diagnosis252": "No Pass",
	"diagnosis253": "Unexecuted",
	"diagnosis254": "It is recommended to continue the watch.",
	"fullscreen2": "Title word exceeds the limit",
	"fullscreen3": "X1X [Up to X2X character(s)]",
	"record1": "Limit to XX character(s)",
	"record2": "Limit to XX pic(s)",
	"plant_detail33": "Plant Name",
	"record3": "Field (Maintenance Detail) is limit to XX character(s)",
	"record4": "Field (Note) is limit to XX character(s)",
	"record5": "Field (Maintenance Detail) is limit to XX pic(s)",
	"record6": "Field (Note) is limit to XX pic(s)",
	"role18": "The external role is a default role, which has partial permissions and cannot be changed. ",
	"record7": "Maintenance detail field cannot be blank",
	"record8": "Add one picture at a time",
	"all5": "SSL authentication failed. Continue to visit?",
	"plant259": "Battery",
	"plant260": "Enter Device SN",
	"me8": "Personal Info",
	"plant261": "Please install File Manager",
	"plant262": "Camera permission is not granted",
	"device25": "No upload records found. Please try to power on the device and connect to server again.",
	"plant271": "Cannot read file: permission denied.",
	"command10": "Enable",
	"command11": "Disable",
	"command12": "Entry Error",
	"command13": "Entry field cannot be blank",
	"plant274": "Sure to remove the device?",
	"product11": "Enter Product Name",
	"plant275": "Authorized Business Units",
	"plant276": "Authorized Users",
	"plant277": "Authorized Internal Members",
	"creat_plant65": "Installed capacity must be greater than 0",
	"task86": "Task starting time cannot be earlier than the current time.",
	"plant278": "Connected Plant",
	"plant279": "Permissions to album are not granded."
}