{
	"manage220": "Gestion d'appareils",
	"plant_detail377": "Consommation totale d'énergie",
	"device_management98": "Il y a des compteurs non configurés dans votre centrale. Veuillez cliquer sur le compteur non configuré pour terminer la configuration, sinon les données du compteur ne s'afficheront pas dans la centrale.",
	"device_management99": "N'est plus affiché",
	"device_management100": "Rappel de configuration pour équipement de compteur",
	"plant258": "Pas de données",
	"me3": "Image de profil",
	"manage336": "Voulez-vous supprimer ce groupe?",
	"plant_detail34": "Revenu total",
	"device_management13": "Tension",
	"device_management14": "Supprimer tout",
	"device218": "Gestion du firmware",
	"plant_detail77": "Veuillez confirmer",
	"report27": "Total",
	"report28": "Sélectionnez au moins un objet",
	"device_management101": "Nom du firmware",
	"device_management102": "Indisponible",
	"app50": "Type de rapport",
	"device_management104": "Hors réseau",
	"device_management106": "Compte",
	"plant_detail378": "Date",
	"plant_detail379": "Segment de temps",
	"device200": " ",
	"device201": "Ajouter",
	"user150": "Confirmer le mot de passe (au moins 6 caractères)",
	"manage337": "Limite de taille XXMB",
	"manage338": "Entrez le numéro entre et XX (maintenez 2 chiffres)",
	"manage339": "Veuillez remplir le formulaire comme indiqué",
	"control38": "Retour",
	"command10": "Activé",
	"command11": "Désactivé",
	"plant278": "Projet connecté"
}